<?php

declare(strict_types=1);

namespace Milpa\Resolver\Tests\Report;

use Milpa\Resolver\Capability\RequirementLevel;
use Milpa\Resolver\Engine\GraphResolver;
use Milpa\Resolver\Input\ResolutionInput;
use Milpa\Resolver\Manifest\AcceptedRisk;
use Milpa\Resolver\Manifest\ContractManifest;
use Milpa\Resolver\Manifest\HostProfile;
use Milpa\Resolver\Manifest\VersionManifest;
use Milpa\Resolver\Report\ErrorCatalog;
use Milpa\Resolver\Report\ResolutionReport;
use Milpa\Resolver\Report\ResolutionStatus;
use Milpa\ValueObjects\Capability\CapabilityProvision;
use Milpa\ValueObjects\Capability\CapabilityRequirement;
use PHPUnit\Framework\TestCase;

/**
 * Freezes the WHOLE serialized {@see \Milpa\Resolver\Report\ResolutionReport} as a public contract —
 * not just its lists — so the report can never decay into "a bag of opaque arrays". Four layers:
 *
 *  1. LISTS — each of the nine lists has one closed schema: an exact, ordered key set, a type per
 *     field, and a closed value domain where one applies (`kind`, `level`, `via`, catalog-bound
 *     `code`).
 *  2. SHELL — the top-level key ORDER is frozen ({@see topLevelKeys()}), `status` is a closed scalar
 *     domain (the four {@see ResolutionStatus} values, all exercised by the corpus), and `metadata`
 *     is a frozen two-field map ({@see metadataSchema()}).
 *  3. NESTED errors[] shapes — `context` keys follow one endorsed order when present
 *     ({@see contextKeyOrder()}; `MILPA_MANIFEST_DRIFT` is exempt, see there), every
 *     `recommendedActions` entry is `type`-first with a closed type domain ({@see actionTypes()}),
 *     and `learn` is the bilingual links map ({@see learnKeys()}).
 *  4. ROUND-TRIP — `toArray(fromArray(toArray($r)))` is byte-identical to `toArray($r)` for the WHOLE
 *     corpus, and where `fromArray()` is deliberately lossy (defensive drops of malformed input,
 *     `recommendedActions` re-derivation) the loss is frozen EXPLICITLY by its own tests.
 *
 * Every example is GENERATED by the engine over the five §15 scenarios plus the legacy/CRM cases —
 * never a hand-written fixture — so every schema is asserted against what the engine actually emits.
 * A test fails on a missing key, an extra undocumented key (both mutation directions are exercised),
 * a wrong type, an out-of-domain value, or a reordered key set; further tests assert the README
 * "Report shapes" tables list exactly these fields and domains, so docs cannot drift from code.
 */
final class ReportShapeContractsTest extends TestCase
{
    /**
     * Codes whose `context` is EXEMPT from the endorsed engine key order: `MILPA_MANIFEST_DRIFT` is
     * caller-emitted ({@see \Milpa\Resolver\Ingest\DriftDetector::toLearnableErrors()}), never built
     * by the engine's errorContext() pass, and carries its own frozen shape — exactly `package` (the
     * drifted package label) and `fields` (the drifted field records) — outside the engine order on
     * purpose: a drift diagnosis identifies a manifest, not a graph requirement.
     */
    private const CONTEXT_ORDER_EXEMPT = ['MILPA_MANIFEST_DRIFT'];
    /**
     * The frozen schema per report list: `list => [field => [type, domain?]]`, in emission order.
     *
     * Type tokens: `string`, `non-empty-string`, `?string` (string or null), `bool`, `string[]`
     * (list of strings), `array[]` (list of arrays), `array` (free-form map). An optional second
     * element closes the value domain: an explicit list of allowed strings, or the sentinel
     * `catalog` (the value must be a known {@see ErrorCatalog} code).
     *
     * @return array<string, array<string, array{0: string, 1?: list<string>|string}>>
     */
    private static function schema(): array
    {
        $levels = array_map(static fn (RequirementLevel $l): string => $l->value, RequirementLevel::cases());

        return [
            'missing' => [
                'kind' => ['non-empty-string', ['contract', 'capability', 'surface-requirement', 'legacy-contract']],
                'id' => ['non-empty-string'],
                'constraint' => ['?string'],
                'level' => ['non-empty-string', $levels],
                'requiredBy' => ['non-empty-string'],
                'surface' => ['?string'],
                'code' => ['non-empty-string', 'catalog'],
                'reason' => ['non-empty-string'],
            ],
            'conflicts' => [
                'kind' => ['non-empty-string', ['capability', 'dependency-cycle']],
                'id' => ['non-empty-string'],
                'code' => ['non-empty-string', 'catalog'],
                'providedBy' => ['string[]'],
                'reason' => ['non-empty-string'],
            ],
            'warnings' => [
                'kind' => ['non-empty-string', ['suggested-capability', 'deprecation', 'surface', 'risk-expiry']],
                'id' => ['non-empty-string'],
                'surface' => ['?string'],
                'code' => ['non-empty-string'],
                'requiredBy' => ['non-empty-string'],
                'fallback' => ['?string'],
                'accepted' => ['bool'],
                'acceptedReason' => ['?string'],
                'acceptanceExpired' => ['bool'],
                'message' => ['string'],
            ],
            'legacy' => [
                'kind' => ['non-empty-string', ['contract', 'capability']],
                'id' => ['non-empty-string'],
                'constraint' => ['non-empty-string'],
                'code' => ['non-empty-string', 'catalog'],
                'providedBy' => ['non-empty-string'],
                'permitted' => ['bool'],
                'reason' => ['non-empty-string'],
            ],
            'resolved' => [
                'kind' => ['non-empty-string', ['contract', 'capability', 'surface']],
                'id' => ['non-empty-string'],
                'constraint' => ['non-empty-string'],
                'level' => ['non-empty-string', $levels],
                'requiredBy' => ['non-empty-string'],
                'providedBy' => ['non-empty-string'],
                'via' => ['non-empty-string', ['direct', 'legacy', 'oneOf']],
            ],
            'loadOrder' => [
                'name' => ['non-empty-string'],
                'version' => ['string'],
            ],
            'migrationHints' => [
                'id' => ['non-empty-string'],
                'from' => ['non-empty-string'],
                'to' => ['?string'],
                'migrationUrl' => ['?string'],
                'message' => ['non-empty-string'],
            ],
            'learnLinks' => [
                'id' => ['non-empty-string'],
                'academy' => ['?string'],
                'migration' => ['?string'],
            ],
            'errors' => [
                'code' => ['non-empty-string', 'catalog'],
                'message' => ['non-empty-string'],
                'why' => ['non-empty-string'],
                'context' => ['array'],
                'fixes' => ['string[]'],
                'recommendedActions' => ['array[]'],
                'learn' => ['array'],
            ],
        ];
    }

    /**
     * The `kind`/`via` values every list is required to exercise, so the schema is proven against the
     * whole domain — not just the one branch that happens to run first.
     *
     * @return array<string, array{field: string, values: list<string>}>
     */
    private static function requiredDomainCoverage(): array
    {
        return [
            'missing' => ['field' => 'kind', 'values' => ['contract', 'capability', 'surface-requirement', 'legacy-contract']],
            'conflicts' => ['field' => 'kind', 'values' => ['capability', 'dependency-cycle']],
            'warnings' => ['field' => 'kind', 'values' => ['suggested-capability', 'deprecation', 'surface', 'risk-expiry']],
            'legacy' => ['field' => 'kind', 'values' => ['contract', 'capability']],
            'resolved' => ['field' => 'via', 'values' => ['direct', 'legacy', 'oneOf']],
        ];
    }

    /**
     * The frozen top-level key ORDER of a serialized report — the exact sequence
     * {@see ResolutionReport::toArray()} emits: `errors[]` leads right after `status` so an agent
     * reads the diagnosis first (spec §20), and `metadata` closes. Previously pinned only in
     * ResolutionReportTest; frozen here so the shell joins the engine === harness === README
     * lockstep.
     *
     * @return list<string>
     */
    private static function topLevelKeys(): array
    {
        return ['status', 'errors', 'resolved', 'loadOrder', 'missing', 'conflicts', 'warnings', 'legacy', 'migrationHints', 'learnLinks', 'metadata'];
    }

    /**
     * The closed `status` domain — the four verdicts of spec §5, in enum declaration order. Written
     * out literally (not derived from the enum) so the harness locks the ENGINE's enum too:
     * {@see testTheStatusDomainMatchesTheEngineEnum} fails if a case is added, removed, or renamed.
     *
     * @return list<string>
     */
    private static function statusDomain(): array
    {
        return ['valid', 'bootable_with_warnings', 'blocked', 'legacy_compatible'];
    }

    /**
     * The frozen `metadata` map: exactly these keys, in this order — the host-profile identity label
     * and the host's free-form metadata passed through verbatim. Nothing else may ride along.
     *
     * @return array<string, string>
     */
    private static function metadataSchema(): array
    {
        return ['hostProfile' => 'non-empty-string', 'hostMetadata' => 'array'];
    }

    /**
     * The endorsed key order of every ENGINE-emitted `errors[].context` (GraphResolver::errorContext):
     * requirement identity first (`id`, `constraint`, the `oneOf` alternatives that widen it), then
     * where (`surface`), then the two parties (`requiredBy`, `providedBy`), then the degradation path
     * (`fallback`), and the host label last. Keys are OPTIONAL — absent fields are omitted, never
     * null — but when present they appear in exactly this relative order. Caller-emitted codes listed
     * in {@see CONTEXT_ORDER_EXEMPT} are outside this order by design.
     *
     * @return list<string>
     */
    private static function contextKeyOrder(): array
    {
        return ['id', 'constraint', 'oneOf', 'surface', 'requiredBy', 'providedBy', 'fallback', 'hostProfile'];
    }

    /**
     * The type of each endorsed context field when present. `providedBy` is the one dual-typed field:
     * a provider label (legacy paths), a candidate-label list (conflicts), or the out-of-range oneOf
     * candidate ids (capability version misses).
     *
     * @return array<string, string>
     */
    private static function contextFieldTypes(): array
    {
        return [
            'id' => 'non-empty-string',
            'constraint' => 'non-empty-string',
            'oneOf' => 'string[]',
            'surface' => 'non-empty-string',
            'requiredBy' => 'non-empty-string',
            'providedBy' => 'string-or-string[]',
            'fallback' => 'non-empty-string',
            'hostProfile' => 'non-empty-string',
        ];
    }

    /**
     * The closed domain of `recommendedActions[].type` — every typed, machine-actionable
     * recommendation {@see \Milpa\Resolver\Report\LearnableArchitectureError} can derive, in
     * first-appearance order of its derivation switch. Every action entry leads with `type`; the
     * remaining keys are code-specific string parameters (`candidates` is the one string-list). An
     * entry with an unknown type, or without `type` first, fails the schema — so the domain can only
     * grow through this freeze.
     *
     * @return list<string>
     */
    private static function actionTypes(): array
    {
        return [
            'install-package',
            'enable-plugin',
            'disable-feature',
            'accept-risk',
            'upgrade-package',
            'adjust-constraint',
            'choose-provider',
            'disable-surface',
            'enable-surface',
            'migrate-contract',
            'allow-legacy-contract',
            'update-host-profile',
            'review-blocking-errors',
            'review-warnings',
            'set-evaluated-at',
            'remove-risk-expiry',
        ];
    }

    /**
     * The frozen `learn` map: the bilingual Academy links, keyed in this order. `academy` and `llms`
     * are REQUIRED on every catalog-built error (the "no dead error" rule — every code teaches and
     * every code is agent-consumable); `artifact` is optional (not every lesson has an artifact).
     * Every present value is exactly the bilingual pair `{es, en}` of non-empty URLs.
     *
     * @return list<string>
     */
    private static function learnKeys(): array
    {
        return ['academy', 'artifact', 'llms'];
    }

    /**
     * Every list carries at least one engine-generated entry, so no schema is asserted over thin air.
     */
    public function testTheCorpusExercisesEveryList(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            self::assertNotSame([], $this->entriesFor($list), "corpus produced no {$list}[] entries");
        }
    }

    /**
     * The corpus exercises every `kind`/`via` value the closed domains name, so the schema is frozen
     * against the full branch space of each list.
     */
    public function testTheCorpusCoversEveryClosedDomainValue(): void
    {
        foreach (self::requiredDomainCoverage() as $list => $coverage) {
            $seen = array_column($this->entriesFor($list), $coverage['field']);
            foreach ($coverage['values'] as $value) {
                self::assertContains($value, $seen, "corpus never produced {$list}[].{$coverage['field']} = {$value}");
            }
        }
    }

    /**
     * Headline contract: every entry of every list has EXACTLY the frozen key set, in order
     * (`assertSame` on `array_keys`). A missing or extra key is caught here.
     */
    public function testEveryEntryHasExactlyTheFrozenKeySetInOrder(): void
    {
        foreach (self::schema() as $list => $fields) {
            $expected = array_keys($fields);
            foreach ($this->entriesFor($list) as $i => $entry) {
                self::assertSame($expected, array_keys($entry), "{$list}[{$i}] key set drifted");
            }
        }
    }

    /**
     * Every field of every entry matches its frozen type and (where closed) its value domain.
     */
    public function testEveryEntryMatchesItsTypesAndDomains(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            foreach ($this->entriesFor($list) as $i => $entry) {
                self::assertSame([], $this->schemaViolations($list, $entry), "{$list}[{$i}] violated its schema");
            }
        }
    }

    /**
     * Mutation check, direction 1 — an EXTRA undocumented key makes the entry fail its schema. Proves
     * the contract rejects silent field growth (the exact decay Rod's review flagged).
     */
    public function testSchemaRejectsAnExtraUndocumentedKey(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            $entry = $this->entriesFor($list)[0];
            $mutated = $entry + ['undocumentedField' => 'sneaky'];

            self::assertNotSame([], $this->schemaViolations($list, $mutated), "{$list}[] accepted an extra key");
        }
    }

    /**
     * Mutation check, direction 2 — a MISSING required key makes the entry fail its schema.
     */
    public function testSchemaRejectsAMissingRequiredKey(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            $entry = $this->entriesFor($list)[0];
            $firstKey = array_key_first($entry);
            $mutated = $entry;
            unset($mutated[$firstKey]);

            self::assertNotSame([], $this->schemaViolations($list, $mutated), "{$list}[] accepted a missing key");
        }
    }

    /**
     * Mutation check, type direction — a value of the wrong type makes the entry fail its schema.
     */
    public function testSchemaRejectsAWronglyTypedValue(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            $entry = $this->entriesFor($list)[0];
            $firstKey = array_key_first($entry);
            $mutated = $entry;
            // A nested array is never a valid value for any first field of any list (all are scalars).
            $mutated[$firstKey] = ['unexpected' => 'array'];

            self::assertNotSame([], $this->schemaViolations($list, $mutated), "{$list}[] accepted a wrong type");
        }
    }

    /**
     * Drift-lock on `warnings[].fallback` (Contrato slice T3), both mutation directions on the field
     * itself: a suggested-capability warning that LOSES the key fails the schema, and a non-string
     * value fails its `?string` type. The corpus assertion below proves the field is exercised with a
     * real (non-null) engine-emitted value, so the lock is never asserted over thin air.
     */
    public function testWarningsFallbackIsDriftLocked(): void
    {
        $entry = null;
        foreach ($this->entriesFor('warnings') as $candidate) {
            if ($candidate['kind'] === 'suggested-capability') {
                $entry = $candidate;

                break;
            }
        }
        self::assertNotNull($entry, 'corpus produced no suggested-capability warning');

        $missingKey = $entry;
        unset($missingKey['fallback']);
        self::assertNotSame([], $this->schemaViolations('warnings', $missingKey), 'warnings[] accepted a missing fallback key');

        $wrongType = $entry;
        $wrongType['fallback'] = 123;
        self::assertNotSame([], $this->schemaViolations('warnings', $wrongType), 'warnings[] accepted a non-string fallback');
    }

    /**
     * The corpus exercises a NON-NULL fallback — a suggestion record that declares its degradation
     * path — so `?string` is proven against a real value, not just the null default.
     */
    public function testTheCorpusExercisesADeclaredFallback(): void
    {
        $fallbacks = array_column($this->entriesFor('warnings'), 'fallback');

        self::assertContains('noop', $fallbacks, 'corpus never produced a warnings[].fallback != null');
        self::assertContains(null, $fallbacks, 'corpus never produced a warnings[].fallback = null');
    }

    /**
     * Mutation check, domain direction — an out-of-domain value for a closed field fails the schema.
     */
    public function testSchemaRejectsAnOutOfDomainValue(): void
    {
        $entry = $this->entriesFor('missing')[0];
        $mutated = $entry;
        $mutated['kind'] = 'not-a-real-kind';

        self::assertNotSame([], $this->schemaViolations('missing', $mutated), 'missing[] accepted an out-of-domain kind');
    }

    /**
     * The README "Report shapes" tables list EXACTLY the frozen fields of each list, in order, AND
     * each field's Type cell normalizes to the exact `[type, domain?]` spec the schema enforces
     * ({@see readmeTypeSpec()}) — the public contract cannot drift from this test's schema in name
     * OR in type.
     */
    public function testReadmeTablesMatchTheFrozenSchemaExactly(): void
    {
        $documented = $this->readmeFieldsByList();

        foreach (self::schema() as $list => $fields) {
            self::assertArrayHasKey($list, $documented, "README has no Report-shapes table for {$list}[]");
            self::assertSame(
                array_keys($fields),
                array_keys($documented[$list]),
                "README {$list}[] table fields drifted from the schema",
            );
            foreach ($fields as $field => $spec) {
                self::assertSame(
                    $spec,
                    self::readmeTypeSpec($documented[$list][$field]),
                    "README {$list}[].{$field} type drifted from the schema",
                );
            }
        }

        self::assertSame(
            array_keys(self::schema()),
            array_keys($documented),
            'README documents a different set of lists than the schema freezes',
        );
    }

    // --- the report shell: top-level order, status domain, metadata map -----------------------------

    /**
     * Every corpus report carries EXACTLY the frozen top-level keys, in order, with a status inside
     * the closed domain and the frozen metadata map — the shell contract over the whole corpus.
     */
    public function testEveryReportHasTheFrozenShell(): void
    {
        foreach ($this->corpus() as $i => $report) {
            self::assertSame([], $this->shellViolations($report), "report[{$i}] shell drifted");
        }
    }

    /**
     * The corpus exercises every status of the closed domain — all four verdicts of spec §5 — so the
     * domain is frozen against real engine emissions, not just the enum's word.
     */
    public function testTheCorpusExercisesEveryStatus(): void
    {
        $seen = array_column($this->corpus(), 'status');
        foreach (self::statusDomain() as $status) {
            self::assertContains($status, $seen, "corpus never produced status = {$status}");
        }
    }

    /**
     * Engine === harness on the status domain: the literal list this harness freezes is exactly what
     * {@see ResolutionStatus} declares, value for value and in declaration order. Renaming, adding, or
     * removing a case breaks the lockstep here even before any corpus input exercises it.
     */
    public function testTheStatusDomainMatchesTheEngineEnum(): void
    {
        self::assertSame(
            self::statusDomain(),
            array_map(static fn (ResolutionStatus $s): string => $s->value, ResolutionStatus::cases()),
        );
    }

    /**
     * Mutation check — a status outside the closed domain fails the shell.
     */
    public function testShellRejectsAnOutOfDomainStatus(): void
    {
        $report = $this->corpus()[0];
        $report['status'] = 'exploded';

        self::assertNotSame([], $this->shellViolations($report), 'shell accepted an out-of-domain status');
    }

    /**
     * Mutation check — REORDERING the top-level keys of a serialized clone fails the shell, even with
     * every key and value intact. The order IS the contract: the same report must render byte-for-byte
     * identically everywhere, with the diagnosis (`errors`) always right after `status`.
     */
    public function testShellRejectsReorderedTopLevelKeys(): void
    {
        $report = $this->corpus()[0];
        $reordered = ['metadata' => $report['metadata']] + $report;

        $canonicalContent = $report;
        ksort($canonicalContent);
        $reorderedContent = $reordered;
        ksort($reorderedContent);
        self::assertSame($canonicalContent, $reorderedContent, 'the mutation must only reorder, never change content');

        self::assertNotSame([], $this->shellViolations($reordered), 'shell accepted reordered top-level keys');
    }

    /**
     * Mutation checks on the frozen metadata map, all three directions: an EXTRA key (the named T4
     * check — nothing may ride along silently), a missing key, and a wrongly-typed value.
     */
    public function testShellRejectsAMutatedMetadataMap(): void
    {
        $report = $this->corpus()[0];

        $extra = $report;
        $extra['metadata']['sneaky'] = 'field';
        self::assertNotSame([], $this->shellViolations($extra), 'shell accepted an extra metadata key');

        $missing = $report;
        unset($missing['metadata']['hostMetadata']);
        self::assertNotSame([], $this->shellViolations($missing), 'shell accepted a missing metadata key');

        $wrongType = $report;
        $wrongType['metadata']['hostProfile'] = 123;
        self::assertNotSame([], $this->shellViolations($wrongType), 'shell accepted a wrongly-typed metadata value');
    }

    // --- the nested errors[] shapes: context, recommendedActions, learn -----------------------------

    /**
     * Every engine-emitted `errors[].context` follows the endorsed key order: present keys are a
     * subsequence of {@see contextKeyOrder()}, correctly typed, with the requirement identity (`id`)
     * and the host label always present. Caller-emitted MILPA_MANIFEST_DRIFT is exempt (see
     * {@see CONTEXT_ORDER_EXEMPT}) — and never emitted by the engine, so the whole corpus is checked.
     */
    public function testEngineEmittedContextsFollowTheEndorsedKeyOrder(): void
    {
        foreach ($this->errorEntries() as $i => $error) {
            self::assertIsString($error['code']);
            self::assertNotContains($error['code'], self::CONTEXT_ORDER_EXEMPT, 'the engine corpus must never emit a caller-emitted code');
            self::assertIsArray($error['context']);

            self::assertSame([], $this->contextViolations($error['context']), "errors[{$i}] context drifted from the endorsed order");
        }
    }

    /**
     * The corpus exercises EVERY endorsed context key somewhere, so the order is proven over the full
     * key space — `oneOf` and `providedBy` ride together on the oneOf version miss, `fallback` on the
     * declared degradation, `surface` on the surface miss — never over thin air.
     */
    public function testTheCorpusExercisesEveryEndorsedContextKey(): void
    {
        $seen = [];
        foreach ($this->errorEntries() as $error) {
            self::assertIsArray($error['context']);
            foreach (array_keys($error['context']) as $key) {
                $seen[$key] = true;
            }
        }

        foreach (self::contextKeyOrder() as $key) {
            self::assertArrayHasKey($key, $seen, "corpus never produced a context carrying `{$key}`");
        }
    }

    /**
     * Mutation checks — a context that DISORDERS two endorsed keys fails, and so does one carrying a
     * key outside the endorsed set.
     */
    public function testContextRejectsDisorderedOrUnknownKeys(): void
    {
        $context = null;
        foreach ($this->errorEntries() as $error) {
            if (is_array($error['context']) && count($error['context']) >= 3) {
                $context = $error['context'];

                break;
            }
        }
        self::assertNotNull($context, 'corpus produced no context with three keys to mutate');

        $keys = array_keys($context);
        $swapped = $context;
        [$swapped[$keys[0]], $swapped[$keys[1]]] = [$context[$keys[1]], $context[$keys[0]]];
        $disordered = [];
        foreach ([$keys[1], $keys[0], ...array_slice($keys, 2)] as $key) {
            $disordered[$key] = $context[$key];
        }
        self::assertNotSame([], $this->contextViolations($disordered), 'context accepted disordered endorsed keys');

        $unknown = $context + ['undocumentedField' => 'sneaky'];
        self::assertNotSame([], $this->contextViolations($unknown), 'context accepted an unknown key');
    }

    /**
     * The documented exemption is real and itself frozen: a caller-emitted MILPA_MANIFEST_DRIFT error
     * (built by DriftDetector, never the engine) carries EXACTLY `package` + `fields` — keys outside
     * the endorsed engine order on purpose, and pinned here so the exemption cannot silently widen.
     */
    public function testManifestDriftContextIsTheExemptFrozenShape(): void
    {
        $drift = ErrorCatalog::for('MILPA_MANIFEST_DRIFT', [
            'package' => 'OAuthPlugin',
            'fields' => [['field' => 'version', 'declared' => '1.0.0', 'actual' => '2.0.0']],
        ])->toArray();

        self::assertContains($drift['code'], self::CONTEXT_ORDER_EXEMPT);
        self::assertSame(['package', 'fields'], array_keys($drift['context']));
        self::assertNotSame([], $this->contextViolations($drift['context']), 'the exemption would be vacuous if the drift context already obeyed the engine order');
    }

    /**
     * Every `recommendedActions` entry across the corpus matches the frozen action shape: `type`
     * first, a known type, and string (or string-list) parameters only.
     */
    public function testEveryRecommendedActionMatchesTheFrozenShape(): void
    {
        $count = 0;
        foreach ($this->errorEntries() as $i => $error) {
            self::assertIsArray($error['recommendedActions']);
            foreach ($error['recommendedActions'] as $action) {
                self::assertIsArray($action);
                self::assertSame([], $this->actionViolations($action), "errors[{$i}] carries a malformed recommendedAction");
                ++$count;
            }
        }

        self::assertGreaterThan(0, $count, 'corpus produced no recommendedActions at all');
    }

    /**
     * The action-domain census: the corpus exercises 13 of the 16 frozen action types — every type
     * the ENGINE can derive. The three exceptions are upper-layer by construction:
     * `update-host-profile`, `review-blocking-errors` and `review-warnings` belong to codes
     * (`MILPA_HOST_PROFILE_OUTDATED`, `MILPA_ARCHITECTURE_GRAPH_BLOCKED`,
     * `MILPA_BOOTABLE_WITH_WARNINGS`) the engine structurally never emits, and a hand-written
     * fixture would break this harness's foundational rule (every example is GENERATED by the
     * engine). Frozen as an exact set so the census can neither silently shrink (a lost corpus
     * path) nor silently grow (a newly engine-reachable type must be recorded here).
     */
    public function testTheCorpusExercisesEveryEngineReachableActionType(): void
    {
        $seen = [];
        foreach ($this->errorEntries() as $error) {
            self::assertIsArray($error['recommendedActions']);
            foreach ($error['recommendedActions'] as $action) {
                self::assertIsArray($action);
                self::assertIsString($action['type']);
                $seen[$action['type']] = true;
            }
        }

        $upperLayerOnly = ['update-host-profile', 'review-blocking-errors', 'review-warnings'];
        self::assertSame(
            array_values(array_diff(self::actionTypes(), $upperLayerOnly)),
            array_values(array_intersect(self::actionTypes(), array_keys($seen))),
            'the engine-proven action census drifted from 13 of 16',
        );
    }

    /**
     * Mutation checks — an action WITHOUT its `type` (the named T4 check), one whose type is unknown,
     * and one whose `type` is not the FIRST key all fail the schema.
     */
    public function testActionRejectsAMissingUnknownOrDemotedType(): void
    {
        $action = null;
        foreach ($this->errorEntries() as $error) {
            self::assertIsArray($error['recommendedActions']);
            if (isset($error['recommendedActions'][0]) && count($error['recommendedActions'][0]) >= 2) {
                $action = $error['recommendedActions'][0];

                break;
            }
        }
        self::assertNotNull($action, 'corpus produced no parameterized action to mutate');

        $missingType = $action;
        unset($missingType['type']);
        self::assertNotSame([], $this->actionViolations($missingType), 'schema accepted an action without its type');

        $unknownType = $action;
        $unknownType['type'] = 'reticulate-splines';
        self::assertNotSame([], $this->actionViolations($unknownType), 'schema accepted an unknown action type');

        $demotedType = ['undocumentedField' => 'sneaky'] + $action;
        self::assertNotSame([], $this->actionViolations($demotedType), 'schema accepted an action whose type is not the first key');
    }

    /**
     * Every `learn` map across the corpus matches the frozen bilingual shape — and the corpus proves
     * `artifact` genuinely optional by exercising it both present and absent.
     */
    public function testEveryLearnMapMatchesTheFrozenBilingualShape(): void
    {
        $withArtifact = 0;
        $withoutArtifact = 0;
        foreach ($this->errorEntries() as $i => $error) {
            self::assertIsArray($error['learn']);
            self::assertSame([], $this->learnViolations($error['learn']), "errors[{$i}] learn map drifted");
            isset($error['learn']['artifact']) ? ++$withArtifact : ++$withoutArtifact;
        }

        self::assertGreaterThan(0, $withArtifact, 'corpus never produced a learn map WITH an artifact link');
        self::assertGreaterThan(0, $withoutArtifact, 'corpus never produced a learn map WITHOUT an artifact link');
    }

    /**
     * Mutation checks — a learn map whose academy link loses `en` (the named T4 check: a bilingual
     * lesson must stay bilingual), one missing `academy` altogether, and one carrying an unknown key
     * all fail the schema.
     */
    public function testLearnRejectsAMonolingualMissingOrUnknownEntry(): void
    {
        $learn = $this->errorEntries()[0]['learn'];
        self::assertIsArray($learn);

        $withoutEn = $learn;
        self::assertIsArray($withoutEn['academy']);
        unset($withoutEn['academy']['en']);
        self::assertNotSame([], $this->learnViolations($withoutEn), 'schema accepted an academy link without en');

        $withoutAcademy = $learn;
        unset($withoutAcademy['academy']);
        self::assertNotSame([], $this->learnViolations($withoutAcademy), 'schema accepted a learn map without academy');

        $unknown = $learn + ['wiki' => ['es' => 'https://example.test/', 'en' => 'https://example.test/en/']];
        self::assertNotSame([], $this->learnViolations($unknown), 'schema accepted an unknown learn key');
    }

    // --- round-trip: toArray(fromArray(toArray($r))) === toArray($r) --------------------------------

    /**
     * The FULL corpus round-trips byte-identically through fromArray(): nothing an engine-emitted
     * report carries is lost or reshaped by rehydration — `recommendedActions` included, because
     * their re-derivation from code + context is deterministic and the context survives verbatim.
     */
    public function testTheWholeCorpusRoundTripsByteIdentically(): void
    {
        foreach ($this->corpus() as $i => $report) {
            self::assertSame(
                json_encode($report),
                json_encode(ResolutionReport::fromArray($report)->toArray()),
                "report[{$i}] did not survive toArray(fromArray(toArray()))",
            );
        }
    }

    /**
     * The one deliberate loss, frozen EXPLICITLY (T4 decision: freeze, don't "fix"): fromArray() is
     * DEFENSIVE against malformed input — a non-record entry in a list is dropped, and a non-map
     * `metadata` collapses to `[]` — because rehydration must never propagate a shape the engine could
     * not have emitted. Well-formed reports are untouched (the corpus round-trip above); this pins the
     * exact behaviour at the malformed boundary so it can never become an accidental data eater.
     */
    public function testFromArrayDropsMalformedInputExplicitly(): void
    {
        $report = $this->corpus()[0];

        $tampered = $report;
        array_unshift($tampered['missing'], 'not-a-record');
        $tampered['metadata'] = 'not-a-map';

        $rehydrated = ResolutionReport::fromArray($tampered);

        self::assertSame($report['missing'], $rehydrated->missing, 'the non-record entry must be dropped, the records kept verbatim');
        self::assertSame([], $rehydrated->metadata, 'non-map metadata must collapse to the empty map');
    }

    /**
     * The second deliberate reshape, frozen EXPLICITLY (T4 decision: keep the derivation, don't
     * store): `recommendedActions` are DERIVED state — {@see \Milpa\Resolver\Report\LearnableArchitectureError::fromArray()}
     * discards the serialized list and toArray() re-derives it from code + context. A hand-tampered
     * action list therefore does NOT survive rehydration: the canonical derivation replaces it. That
     * is the contract — the single source of a recommendation is the catalog logic, never a mutable
     * array field.
     */
    public function testTamperedRecommendedActionsAreReplacedByTheCanonicalDerivation(): void
    {
        $report = null;
        foreach ($this->corpus() as $candidate) {
            if ($candidate['errors'] !== []) {
                $report = $candidate;

                break;
            }
        }
        self::assertNotNull($report, 'corpus produced no report with errors');

        $tampered = $report;
        self::assertIsArray($tampered['errors'][0]);
        $tampered['errors'][0]['recommendedActions'] = [['type' => 'reticulate-splines']];

        $again = ResolutionReport::fromArray($tampered)->toArray();

        self::assertIsArray($again['errors'][0]);
        self::assertSame(
            $report['errors'][0]['recommendedActions'],
            $again['errors'][0]['recommendedActions'],
            'rehydration must re-derive the canonical actions, not preserve the tampered list',
        );
    }

    /**
     * The README documents every non-list contract exactly as this harness freezes it: the top-level
     * key order, the status domain, the metadata map, the endorsed context order, the action-type
     * domain, and the learn keys — name for name, in order. The third leg of the drift-lock.
     */
    public function testReadmeDocumentsTheNonListContractsExactly(): void
    {
        self::assertSame(self::topLevelKeys(), $this->readmeContractFields('ResolutionReport'), 'README top-level key order drifted');
        self::assertSame(self::statusDomain(), $this->readmeContractFields('status'), 'README status domain drifted');
        self::assertSame(array_keys(self::metadataSchema()), $this->readmeContractFields('metadata'), 'README metadata fields drifted');
        self::assertSame(self::contextKeyOrder(), $this->readmeContractFields('errors[].context'), 'README context key order drifted');
        self::assertSame(self::actionTypes(), $this->readmeContractFields('errors[].recommendedActions[]'), 'README action-type domain drifted');
        self::assertSame(self::learnKeys(), $this->readmeContractFields('errors[].learn'), 'README learn keys drifted');
    }

    // --- helpers -----------------------------------------------------------------------------------

    /**
     * Validate a serialized report's SHELL: exact top-level key order, closed status domain, frozen
     * metadata map (exact ordered keys + types). Key-order drift short-circuits, exactly like the
     * per-list validator.
     *
     * @param array<string, mixed> $report
     *
     * @return list<string>
     */
    private function shellViolations(array $report): array
    {
        if (array_keys($report) !== self::topLevelKeys()) {
            return [sprintf('top-level keys [%s] != frozen order [%s]', implode(',', array_keys($report)), implode(',', self::topLevelKeys()))];
        }

        $violations = [];
        if (!is_string($report['status']) || !in_array($report['status'], self::statusDomain(), true)) {
            $violations[] = sprintf('status: value "%s" is out of domain', is_scalar($report['status']) ? (string) $report['status'] : get_debug_type($report['status']));
        }

        if (!is_array($report['metadata'])) {
            $violations[] = sprintf('metadata: expected map, got %s', get_debug_type($report['metadata']));

            return $violations;
        }
        if (array_keys($report['metadata']) !== array_keys(self::metadataSchema())) {
            $violations[] = sprintf('metadata keys [%s] != frozen [%s]', implode(',', array_keys($report['metadata'])), implode(',', array_keys(self::metadataSchema())));

            return $violations;
        }
        foreach (self::metadataSchema() as $field => $type) {
            if (!$this->typeOk($type, $report['metadata'][$field])) {
                $violations[] = sprintf('metadata.%s: expected type %s, got %s', $field, $type, get_debug_type($report['metadata'][$field]));
            }
        }

        return $violations;
    }

    /**
     * Validate an engine-emitted context against the endorsed key order: every key known, positions
     * strictly ascending (a subsequence of the order), types right, and the two anchors — `id` and
     * `hostProfile` — always present.
     *
     * @param array<string, mixed> $context
     *
     * @return list<string>
     */
    private function contextViolations(array $context): array
    {
        $order = self::contextKeyOrder();
        $types = self::contextFieldTypes();

        $violations = [];
        foreach (['id', 'hostProfile'] as $anchor) {
            if (!array_key_exists($anchor, $context)) {
                $violations[] = sprintf('context is missing its `%s` anchor', $anchor);
            }
        }

        $lastPosition = -1;
        foreach ($context as $key => $value) {
            $position = array_search($key, $order, true);
            if ($position === false) {
                $violations[] = sprintf('context key `%s` is not in the endorsed order', $key);

                continue;
            }
            if ($position <= $lastPosition) {
                $violations[] = sprintf('context key `%s` is out of the endorsed order', $key);
            }
            $lastPosition = $position;

            if (!$this->typeOk($types[$key], $value)) {
                $violations[] = sprintf('context.%s: expected type %s, got %s', $key, $types[$key], get_debug_type($value));
            }
        }

        return $violations;
    }

    /**
     * Validate one recommendedActions entry: `type` FIRST, inside the closed type domain, and every
     * parameter a string or a list of strings.
     *
     * @param array<string, mixed> $action
     *
     * @return list<string>
     */
    private function actionViolations(array $action): array
    {
        if (array_key_first($action) !== 'type') {
            return [sprintf('action leads with `%s`, not `type`', (string) array_key_first($action))];
        }

        $violations = [];
        if (!is_string($action['type']) || !in_array($action['type'], self::actionTypes(), true)) {
            $violations[] = sprintf('action type "%s" is out of domain', is_scalar($action['type']) ? (string) $action['type'] : get_debug_type($action['type']));
        }

        foreach ($action as $key => $value) {
            if ($key === 'type') {
                continue;
            }
            if (!$this->typeOk('string-or-string[]', $value)) {
                $violations[] = sprintf('action.%s: expected a string or list of strings, got %s', $key, get_debug_type($value));
            }
        }

        return $violations;
    }

    /**
     * Validate one learn map: keys a subsequence of the frozen order, `academy` + `llms` required,
     * every value the exact bilingual `{es, en}` pair of non-empty strings.
     *
     * @param array<string, mixed> $learn
     *
     * @return list<string>
     */
    private function learnViolations(array $learn): array
    {
        $order = self::learnKeys();

        $violations = [];
        foreach (['academy', 'llms'] as $required) {
            if (!array_key_exists($required, $learn)) {
                $violations[] = sprintf('learn is missing its required `%s` link', $required);
            }
        }

        $lastPosition = -1;
        foreach ($learn as $key => $value) {
            $position = array_search($key, $order, true);
            if ($position === false) {
                $violations[] = sprintf('learn key `%s` is not in the frozen set', $key);

                continue;
            }
            if ($position <= $lastPosition) {
                $violations[] = sprintf('learn key `%s` is out of the frozen order', $key);
            }
            $lastPosition = $position;

            if (!is_array($value) || array_keys($value) !== ['es', 'en']) {
                $violations[] = sprintf('learn.%s: expected the exact bilingual {es, en} pair', $key);

                continue;
            }
            foreach ($value as $lang => $url) {
                if (!is_string($url) || $url === '') {
                    $violations[] = sprintf('learn.%s.%s: expected a non-empty URL', $key, $lang);
                }
            }
        }

        return $violations;
    }

    /**
     * Every serialized errors[] entry across the whole corpus.
     *
     * @return list<array<string, mixed>>
     */
    private function errorEntries(): array
    {
        return $this->entriesFor('errors');
    }

    /**
     * Collect every engine-generated entry for one report list across the whole corpus.
     *
     * @return list<array<string, mixed>>
     */
    private function entriesFor(string $list): array
    {
        $out = [];
        foreach ($this->corpus() as $report) {
            foreach ($report[$list] as $entry) {
                self::assertIsArray($entry);
                /** @var array<string, mixed> $entry */
                $out[] = $entry;
            }
        }

        return $out;
    }

    /**
     * The engine-generated corpus: each case is resolved and serialized, together covering every list,
     * every `kind`, and every `via`.
     *
     * @return list<array<string, mixed>>
     */
    private function corpus(): array
    {
        $resolver = new GraphResolver();
        $reports = [];
        foreach ($this->inputs() as $input) {
            $reports[] = $resolver->resolve($input)->toArray();
        }

        return $reports;
    }

    /**
     * The materialized inputs behind the corpus — the five §15 scenarios plus the constraint, oneOf,
     * oneOf-version-miss, known-package version-miss, deprecation, contract-manifest,
     * legacy-capability and CRM-like cases — together exercising every list, every closed domain
     * value, all four statuses, every endorsed context key, and every engine-reachable action type
     * (13 of the 16 frozen — see {@see testTheCorpusExercisesEveryEngineReachableActionType}).
     *
     * @return list<ResolutionInput>
     */
    private function inputs(): array
    {
        return [
            // §15-1 — missing required capability (missing:capability, resolved:capability, errors).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['command.provider', 'tool.registry']),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('tool.registry', 'Tool\\Registry', '0.1.0')],
                capabilityRequirements: [],
            ),
            // A required contract nobody implements (missing:contract, MILPA_CONTRACT_MISSING).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['milpa.runtime@0.3']),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A contract implemented only out of range (missing:contract, MILPA_CONTRACT_VERSION_UNSUPPORTED).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['milpa.persistence@^2.0']),
                versionManifests: [
                    new VersionManifest('milpa/persistence', '1.4.0', ['implements' => ['milpa.persistence@1.4.0']], ['provides' => []]),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // §15-2 — suggested capability missing (warnings:suggested-capability, resolved:capability).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['command.provider']),
                versionManifests: [
                    new VersionManifest(
                        package: 'milpa/command',
                        version: '0.1.0',
                        contracts: ['implements' => ['milpa.command@0.1']],
                        capabilities: [
                            // Same id also arrives as a typed provision below — both records opt out
                            // of §3.1's exclusive default so this stays a warnings-only scenario.
                            'provides' => [['id' => 'command.provider', 'interface' => 'Cmd', 'contractVersion' => '0.1.0', 'exclusive' => false]],
                            'requires' => [],
                            'suggests' => ['audit.sink'],
                        ],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('command.provider', 'Cmd', '0.1.0', exclusive: false)],
                capabilityRequirements: [],
            ),
            // §15-3 — legacy contract active (legacy:contract, migrationHints, resolved via=legacy).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['command.host@0.0'], allowedLegacyContracts: ['command.host']),
                versionManifests: [
                    new VersionManifest(
                        package: 'legacy/command-host',
                        version: '0.0.1',
                        contracts: ['implements' => ['command.host@0.0'], 'requires' => []],
                        capabilities: ['provides' => [], 'requires' => [], 'suggests' => []],
                        metadata: ['shape' => 'legacy-contracts'],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A legacy contract the host does NOT permit (allowedLegacyContracts: []) — the T3 gate: it
            // blocks via a missing[] legacy-contract entry (MILPA_LEGACY_NOT_ALLOWED, constraint null),
            // while the denial stays visible in legacy[] as permitted:false. Exercises the new missing
            // kind and proves constraint is genuinely nullable here.
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['command.host@0.0'], allowedLegacyContracts: []),
                versionManifests: [
                    new VersionManifest(
                        package: 'legacy/command-host',
                        version: '0.0.1',
                        contracts: ['implements' => ['command.host@0.0'], 'requires' => []],
                        capabilities: ['provides' => [], 'requires' => [], 'suggests' => []],
                        metadata: ['shape' => 'legacy-contracts'],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A legacy-shaped manifest that PROVIDES a required capability (legacy:capability, resolved via=legacy).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['legacy.cap'], allowedLegacyContracts: ['*']),
                versionManifests: [
                    new VersionManifest(
                        package: 'legacy/cap-host',
                        version: '0.0.1',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => [['id' => 'legacy.cap', 'interface' => 'L', 'contractVersion' => '0.0.1']]],
                        metadata: ['shape' => 'legacy-contracts'],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // §15-4 — unmet surface requirement (missing:surface-requirement).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', enabledSurfaces: ['mcp']),
                versionManifests: [
                    new VersionManifest('milpa/mcp-server', '0.1.0', ['implements' => []], ['provides' => []], surfaces: ['supports' => ['mcp']]),
                ],
                contractManifests: [],
                capabilityProvisions: [
                    new CapabilityProvision('tool.registry', 'I', '0.1.0'),
                    new CapabilityProvision('principal.resolver', 'I', '0.1.0'),
                ],
                capabilityRequirements: [],
                activeSurfaces: ['mcp'],
                environment: [
                    'surfaces' => [
                        ['surface' => 'mcp', 'requires' => ['tool.registry', 'mcp.transport', 'principal.resolver'], 'warnings' => []],
                    ],
                ],
            ),
            // §15-5 — exclusive conflict (conflicts, errors).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['persistence.store']),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [
                    new CapabilityProvision('persistence.store', 'Store', '0.1.0', service: 'App\\MysqlStore', exclusive: true),
                    new CapabilityProvision('persistence.store', 'Store', '0.1.0', service: 'App\\SqliteStore', exclusive: true),
                ],
                capabilityRequirements: [],
            ),
            // A oneOf requirement satisfied by its alternative (resolved via=oneOf).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07'),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('log.syslog', 'Log', '0.1.0', service: 'App\\SyslogLogger')],
                capabilityRequirements: [new CapabilityRequirement('log.sink', 'Log', '*', ['log.file', 'log.syslog'])],
            ),
            // A declared deprecation (warnings:deprecation, errors).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07'),
                versionManifests: [
                    new VersionManifest('legacy/thing', '1.0.0', ['implements' => []], ['provides' => []], deprecations: ['old.command.host']),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A contract manifest that wants an un-enabled surface (warnings:surface MILPA_SURFACE_NOT_ENABLED,
            // resolved:contract & capability-via-contract, learnLinks with academy + migration).
            new ResolutionInput(
                hostProfile: new HostProfile(
                    name: 'agent-ready',
                    version: '2026.07',
                    requiredContracts: ['milpa.command@0.1'],
                    requiredCapabilities: ['command.provider'],
                    enabledSurfaces: ['cli'],
                ),
                versionManifests: [
                    new VersionManifest('milpa/command', '0.1.0', ['implements' => ['milpa.command@0.1']], ['provides' => []]),
                ],
                contractManifests: [
                    new ContractManifest(
                        id: 'milpa.command',
                        version: '0.1',
                        requiresCapabilities: ['event.dispatcher'],
                        providesCapabilities: ['command.provider'],
                        suggestsCapabilities: ['audit.sink'],
                        surfaceRequirements: ['telegram'],
                        academyUrl: 'https://academy.milpa.lat/learn/fundamentos/contratos-grafo/',
                        migrationUrl: 'https://academy.milpa.lat/artifacts/#atomo',
                    ),
                ],
                capabilityProvisions: [new CapabilityProvision('event.dispatcher', 'E', '0.1.0')],
                capabilityRequirements: [],
                activeSurfaces: ['cli'],
            ),
            // An enabled surface fully satisfied but carrying a declared warning (resolved:surface,
            // warnings:surface with an author-defined open code).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', enabledSurfaces: ['http']),
                versionManifests: [
                    new VersionManifest('milpa/http', '0.1.0', ['implements' => []], ['provides' => []], surfaces: ['supports' => ['http']]),
                ],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('http.router', 'R', '0.1.0')],
                capabilityRequirements: [],
                activeSurfaces: ['http'],
                environment: [
                    'surfaces' => [
                        [
                            'surface' => 'http',
                            'requires' => ['http.router'],
                            'warnings' => [
                                ['code' => 'HTTP_SCOPES_NOT_ENFORCED', 'message' => 'HTTP routes do not enforce Operation scopes in this profile.'],
                            ],
                        ],
                    ],
                ],
            ),
            // A dependency cycle (conflicts:dependency-cycle, MILPA_DEPENDENCY_CYCLE, status blocked):
            // cycle/a and cycle/b require each other's capability, so neither can boot first; the
            // independent third package keeps loadOrder[] populated while the members stay out of it.
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07'),
                versionManifests: [
                    new VersionManifest(
                        package: 'cycle/a',
                        version: '1.0.0',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => ['cap.a'], 'requires' => ['cap.b']],
                    ),
                    new VersionManifest(
                        package: 'cycle/b',
                        version: '1.0.0',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => ['cap.b'], 'requires' => ['cap.a']],
                    ),
                    new VersionManifest(
                        package: 'cycle/standalone',
                        version: '1.0.0',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => []],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // The Contrato T3 teaching paths together: a capability provided only out of range
            // (missing:capability, MILPA_CAPABILITY_VERSION_UNSUPPORTED — its own code, not the
            // contract one), a oneOf requirement exhausted (errors[].context.oneOf), and a suggested
            // capability whose record declares a fallback (warnings:suggested-capability with a
            // non-null `fallback` — the drift-locked field).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['cache.store@^2.0']),
                versionManifests: [
                    new VersionManifest(
                        package: 'milpa/audit',
                        version: '0.1.0',
                        contracts: ['implements' => []],
                        capabilities: [
                            'provides' => [],
                            'suggests' => [['id' => 'audit.sink', 'interface' => 'Audit\\Sink', 'constraint' => '*', 'fallback' => 'noop']],
                        ],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('cache.store', 'Cache', '1.0.0', service: 'App\\ArrayCache')],
                capabilityRequirements: [new CapabilityRequirement('log.sink', 'Log', '*', ['log.file', 'log.syslog'])],
            ),
            // The T4 wording-fix path (inherited agenda 1): a oneOf requirement whose ONLY existing
            // candidate sits out of the consumer's range — the version-miss error context carries
            // `oneOf` AND `providedBy` (which candidate fell out of range) together, completing the
            // corpus coverage of the endorsed context key order.
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07'),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('log.syslog', 'Log', '1.0.0', service: 'App\\SyslogLogger')],
                capabilityRequirements: [new CapabilityRequirement('log.sink', 'Log', '^2.0', ['log.syslog'])],
            ),
            // The T4 reviewer's F1 (release prep): the SAME version-miss code, but on a
            // KNOWN_PACKAGES id — `tool.registry` maps to milpa/tool-runtime — so the error derives
            // the `upgrade-package` recommendedAction naming the concrete package. Takes the
            // engine-proven action census to 13 of 16 (see
            // {@see testTheCorpusExercisesEveryEngineReachableActionType} for the remaining three).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['tool.registry@^2.0']),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('tool.registry', 'Tool\\Registry', '0.1.0')],
                capabilityRequirements: [],
            ),
            // An accepted risk with an expiry but NO evaluatedAt clock (warnings:risk-expiry — the
            // MILPA_RISK_EXPIRY_UNEVALUATED oversight — plus the accepted surface warning it rides on).
            new ResolutionInput(
                hostProfile: new HostProfile(
                    name: 'agent-ready',
                    version: '2026.07',
                    enabledSurfaces: ['http'],
                    acceptedRisks: [new AcceptedRisk('HTTP_SCOPES_NOT_ENFORCED', 'Enforced at the gateway; reviewed 2026-07.', '2026-12-31')],
                ),
                versionManifests: [
                    new VersionManifest('milpa/http', '0.1.0', ['implements' => []], ['provides' => []], surfaces: ['supports' => ['http']]),
                ],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('http.router', 'R', '0.1.0')],
                capabilityRequirements: [],
                activeSurfaces: ['http'],
                environment: [
                    'surfaces' => [
                        [
                            'surface' => 'http',
                            'requires' => ['http.router'],
                            'warnings' => [
                                ['code' => 'HTTP_SCOPES_NOT_ENFORCED', 'message' => 'HTTP routes do not enforce Operation scopes in this profile.'],
                            ],
                        ],
                    ],
                ],
            ),
        ];
    }

    /**
     * Validate one entry against its list schema; returns a list of human-readable violations (empty
     * when the entry conforms). Key-set drift short-circuits: once the shape is wrong, per-field type
     * noise would only obscure the real fault.
     *
     * @param array<string, mixed> $entry
     *
     * @return list<string>
     */
    private function schemaViolations(string $list, array $entry): array
    {
        $schema = self::schema()[$list];
        $expectedKeys = array_keys($schema);
        if (array_keys($entry) !== $expectedKeys) {
            return [sprintf('keys [%s] != expected [%s]', implode(',', array_keys($entry)), implode(',', $expectedKeys))];
        }

        $violations = [];
        foreach ($schema as $field => $spec) {
            $type = $spec[0];
            $domain = $spec[1] ?? null;
            $value = $entry[$field];

            if (!$this->typeOk($type, $value)) {
                $violations[] = sprintf('%s: expected type %s, got %s', $field, $type, get_debug_type($value));

                continue;
            }

            if ($domain !== null && is_string($value)) {
                $allowed = $domain === 'catalog' ? ErrorCatalog::codes() : $domain;
                if (!in_array($value, $allowed, true)) {
                    $violations[] = sprintf('%s: value "%s" is out of domain', $field, $value);
                }
            }
        }

        return $violations;
    }

    private function typeOk(string $type, mixed $value): bool
    {
        return match ($type) {
            'string' => is_string($value),
            'non-empty-string' => is_string($value) && $value !== '',
            '?string' => $value === null || is_string($value),
            'bool' => is_bool($value),
            'string[]' => $this->isListOf($value, 'is_string'),
            'string-or-string[]' => is_string($value) || $this->isListOf($value, 'is_string'),
            'array[]' => $this->isListOf($value, 'is_array'),
            'array' => is_array($value),
            default => false,
        };
    }

    /**
     * @param callable(mixed): bool $predicate
     */
    private function isListOf(mixed $value, callable $predicate): bool
    {
        if (!is_array($value) || !array_is_list($value)) {
            return false;
        }
        foreach ($value as $item) {
            if (!$predicate($item)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Parse the README "Report shapes" section: for each `#### `list[]`` subsection, the ordered
     * `field => Type cell` map taken from the first two columns of its table (the raw Type cell —
     * escaped pipes included — is normalized by {@see readmeTypeSpec()}).
     *
     * @return array<string, array<string, string>>
     */
    private function readmeFieldsByList(): array
    {
        $md = file_get_contents(dirname(__DIR__, 2) . '/README.md');
        self::assertIsString($md, 'README.md is unreadable');

        $start = strpos($md, '## Report shapes');
        self::assertNotFalse($start, 'README has no "## Report shapes" section');
        $section = substr($md, $start);
        $nextH2 = strpos($section, "\n## ", 4);
        if ($nextH2 !== false) {
            $section = substr($section, 0, $nextH2);
        }

        preg_match_all('/####\s+`([a-zA-Z]+)\[\]`(.*?)(?=\n####|\z)/s', $section, $blocks, PREG_SET_ORDER);

        $out = [];
        foreach ($blocks as $block) {
            $list = $block[1];
            preg_match_all('/^\|\s*`([^`]+)`\s*\|\s*((?:[^|\\\\]|\\\\.)*?)\s*\|/m', $block[2], $rows, PREG_SET_ORDER);
            $out[$list] = [];
            foreach ($rows as $row) {
                $out[$list][$row[1]] = $row[2];
            }
        }

        return $out;
    }

    /**
     * Translate one README Type cell into the schema's `[type, domain?]` spec, so the parity test
     * compares TYPES, not just field names. Three notations, nothing else: a lone backticked token
     * is the type itself (`non-empty-string`, `?string`, `bool`, `string[]`, `array[]`, `array`,
     * `string`); `<type> (catalog)` marks the catalog-bound value domain; and two or more literal
     * values separated by `\|` are the closed-domain notation — a `non-empty-string` restricted to
     * exactly those values, in that order.
     *
     * @return array{0: string, 1?: list<string>|string}
     */
    private static function readmeTypeSpec(string $cell): array
    {
        $tokens = array_map(
            static fn (string $token): string => trim($token, '` '),
            preg_split('/\s*\\\\\|\s*/', trim($cell)) ?: [],
        );

        if (count($tokens) > 1) {
            return ['non-empty-string', $tokens];
        }

        if (str_ends_with($tokens[0], ' (catalog)')) {
            return [substr($tokens[0], 0, -strlen(' (catalog)')), 'catalog'];
        }

        return [$tokens[0]];
    }

    /**
     * Parse one NON-LIST contract section of the README "Report shapes" chapter — the convention the
     * T4 freeze added on top of the list tables: a `#### `heading`` subsection (`ResolutionReport`,
     * `status`, `metadata`, `errors[].context`, `errors[].recommendedActions[]`, `errors[].learn`)
     * whose table's first column carries the frozen names, in order. The list parser above stays
     * byte-compatible: its pattern only matches plain `name[]` headings, which none of these are.
     *
     * @return list<string>
     */
    private function readmeContractFields(string $heading): array
    {
        $md = file_get_contents(dirname(__DIR__, 2) . '/README.md');
        self::assertIsString($md, 'README.md is unreadable');

        $start = strpos($md, '## Report shapes');
        self::assertNotFalse($start, 'README has no "## Report shapes" section');
        $section = substr($md, $start);
        $nextH2 = strpos($section, "\n## ", 4);
        if ($nextH2 !== false) {
            $section = substr($section, 0, $nextH2);
        }

        $matched = preg_match(
            '/####\s+`' . preg_quote($heading, '/') . '`(.*?)(?=\n####|\z)/s',
            $section,
            $block,
        );
        self::assertSame(1, $matched, "README has no `{$heading}` contract section");

        preg_match_all('/^\|\s*`([^`]+)`\s*\|/m', $block[1], $rows);

        return $rows[1];
    }
}
