<?php

declare(strict_types=1);

namespace Milpa\Resolver\Tests\Report;

use Milpa\Resolver\Capability\RequirementLevel;
use Milpa\Resolver\Engine\GraphResolver;
use Milpa\Resolver\Input\ResolutionInput;
use Milpa\Resolver\Manifest\AcceptedRisk;
use Milpa\Resolver\Manifest\ContractManifest;
use Milpa\Resolver\Manifest\HostProfile;
use Milpa\Resolver\Manifest\VersionManifest;
use Milpa\Resolver\Report\ErrorCatalog;
use Milpa\ValueObjects\Capability\CapabilityProvision;
use Milpa\ValueObjects\Capability\CapabilityRequirement;
use PHPUnit\Framework\TestCase;

/**
 * Freezes the shape of every entry in every {@see \Milpa\Resolver\Report\ResolutionReport} list, so
 * the report can never decay into "a bag of opaque arrays". Each list has one closed schema: an exact,
 * ordered key set, a type per field, and a closed value domain where one applies (`kind`, `level`,
 * `via`, and catalog-bound `code`). Every example is GENERATED by the engine over the five §15
 * scenarios plus the legacy/CRM cases — never a hand-written fixture — so the schema is asserted
 * against what the engine actually emits. A test fails on a missing key, an extra undocumented key
 * (both mutation directions are exercised), a wrong type, or an out-of-domain value; a further test
 * asserts the README "Report shapes" tables list exactly these fields, so docs cannot drift from code.
 */
final class ReportShapeContractsTest extends TestCase
{
    /**
     * The frozen schema per report list: `list => [field => [type, domain?]]`, in emission order.
     *
     * Type tokens: `string`, `non-empty-string`, `?string` (string or null), `bool`, `string[]`
     * (list of strings), `array[]` (list of arrays), `array` (free-form map). An optional second
     * element closes the value domain: an explicit list of allowed strings, or the sentinel
     * `catalog` (the value must be a known {@see ErrorCatalog} code).
     *
     * @return array<string, array<string, array{0: string, 1?: list<string>|string}>>
     */
    private static function schema(): array
    {
        $levels = array_map(static fn (RequirementLevel $l): string => $l->value, RequirementLevel::cases());

        return [
            'missing' => [
                'kind' => ['non-empty-string', ['contract', 'capability', 'surface-requirement', 'legacy-contract']],
                'id' => ['non-empty-string'],
                'constraint' => ['?string'],
                'level' => ['non-empty-string', $levels],
                'requiredBy' => ['non-empty-string'],
                'surface' => ['?string'],
                'code' => ['non-empty-string', 'catalog'],
                'reason' => ['non-empty-string'],
            ],
            'conflicts' => [
                'kind' => ['non-empty-string', ['capability', 'dependency-cycle']],
                'id' => ['non-empty-string'],
                'code' => ['non-empty-string', 'catalog'],
                'providedBy' => ['string[]'],
                'reason' => ['non-empty-string'],
            ],
            'warnings' => [
                'kind' => ['non-empty-string', ['suggested-capability', 'deprecation', 'surface', 'risk-expiry']],
                'id' => ['non-empty-string'],
                'surface' => ['?string'],
                'code' => ['non-empty-string'],
                'requiredBy' => ['non-empty-string'],
                'accepted' => ['bool'],
                'acceptedReason' => ['?string'],
                'acceptanceExpired' => ['bool'],
                'message' => ['string'],
            ],
            'legacy' => [
                'kind' => ['non-empty-string', ['contract', 'capability']],
                'id' => ['non-empty-string'],
                'constraint' => ['non-empty-string'],
                'code' => ['non-empty-string', 'catalog'],
                'providedBy' => ['non-empty-string'],
                'permitted' => ['bool'],
                'reason' => ['non-empty-string'],
            ],
            'resolved' => [
                'kind' => ['non-empty-string', ['contract', 'capability', 'surface']],
                'id' => ['non-empty-string'],
                'constraint' => ['non-empty-string'],
                'level' => ['non-empty-string', $levels],
                'requiredBy' => ['non-empty-string'],
                'providedBy' => ['non-empty-string'],
                'via' => ['non-empty-string', ['direct', 'legacy', 'oneOf']],
            ],
            'loadOrder' => [
                'name' => ['non-empty-string'],
                'version' => ['string'],
            ],
            'migrationHints' => [
                'id' => ['non-empty-string'],
                'from' => ['non-empty-string'],
                'to' => ['?string'],
                'migrationUrl' => ['?string'],
                'message' => ['non-empty-string'],
            ],
            'learnLinks' => [
                'id' => ['non-empty-string'],
                'academy' => ['?string'],
                'migration' => ['?string'],
            ],
            'errors' => [
                'code' => ['non-empty-string', 'catalog'],
                'message' => ['non-empty-string'],
                'why' => ['non-empty-string'],
                'context' => ['array'],
                'fixes' => ['string[]'],
                'recommendedActions' => ['array[]'],
                'learn' => ['array'],
            ],
        ];
    }

    /**
     * The `kind`/`via` values every list is required to exercise, so the schema is proven against the
     * whole domain — not just the one branch that happens to run first.
     *
     * @return array<string, array{field: string, values: list<string>}>
     */
    private static function requiredDomainCoverage(): array
    {
        return [
            'missing' => ['field' => 'kind', 'values' => ['contract', 'capability', 'surface-requirement', 'legacy-contract']],
            'conflicts' => ['field' => 'kind', 'values' => ['capability', 'dependency-cycle']],
            'warnings' => ['field' => 'kind', 'values' => ['suggested-capability', 'deprecation', 'surface', 'risk-expiry']],
            'legacy' => ['field' => 'kind', 'values' => ['contract', 'capability']],
            'resolved' => ['field' => 'via', 'values' => ['direct', 'legacy', 'oneOf']],
        ];
    }

    /**
     * Every list carries at least one engine-generated entry, so no schema is asserted over thin air.
     */
    public function testTheCorpusExercisesEveryList(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            self::assertNotSame([], $this->entriesFor($list), "corpus produced no {$list}[] entries");
        }
    }

    /**
     * The corpus exercises every `kind`/`via` value the closed domains name, so the schema is frozen
     * against the full branch space of each list.
     */
    public function testTheCorpusCoversEveryClosedDomainValue(): void
    {
        foreach (self::requiredDomainCoverage() as $list => $coverage) {
            $seen = array_column($this->entriesFor($list), $coverage['field']);
            foreach ($coverage['values'] as $value) {
                self::assertContains($value, $seen, "corpus never produced {$list}[].{$coverage['field']} = {$value}");
            }
        }
    }

    /**
     * Headline contract: every entry of every list has EXACTLY the frozen key set, in order
     * (`assertSame` on `array_keys`). A missing or extra key is caught here.
     */
    public function testEveryEntryHasExactlyTheFrozenKeySetInOrder(): void
    {
        foreach (self::schema() as $list => $fields) {
            $expected = array_keys($fields);
            foreach ($this->entriesFor($list) as $i => $entry) {
                self::assertSame($expected, array_keys($entry), "{$list}[{$i}] key set drifted");
            }
        }
    }

    /**
     * Every field of every entry matches its frozen type and (where closed) its value domain.
     */
    public function testEveryEntryMatchesItsTypesAndDomains(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            foreach ($this->entriesFor($list) as $i => $entry) {
                self::assertSame([], $this->schemaViolations($list, $entry), "{$list}[{$i}] violated its schema");
            }
        }
    }

    /**
     * Mutation check, direction 1 — an EXTRA undocumented key makes the entry fail its schema. Proves
     * the contract rejects silent field growth (the exact decay Rod's review flagged).
     */
    public function testSchemaRejectsAnExtraUndocumentedKey(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            $entry = $this->entriesFor($list)[0];
            $mutated = $entry + ['undocumentedField' => 'sneaky'];

            self::assertNotSame([], $this->schemaViolations($list, $mutated), "{$list}[] accepted an extra key");
        }
    }

    /**
     * Mutation check, direction 2 — a MISSING required key makes the entry fail its schema.
     */
    public function testSchemaRejectsAMissingRequiredKey(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            $entry = $this->entriesFor($list)[0];
            $firstKey = array_key_first($entry);
            $mutated = $entry;
            unset($mutated[$firstKey]);

            self::assertNotSame([], $this->schemaViolations($list, $mutated), "{$list}[] accepted a missing key");
        }
    }

    /**
     * Mutation check, type direction — a value of the wrong type makes the entry fail its schema.
     */
    public function testSchemaRejectsAWronglyTypedValue(): void
    {
        foreach (array_keys(self::schema()) as $list) {
            $entry = $this->entriesFor($list)[0];
            $firstKey = array_key_first($entry);
            $mutated = $entry;
            // A nested array is never a valid value for any first field of any list (all are scalars).
            $mutated[$firstKey] = ['unexpected' => 'array'];

            self::assertNotSame([], $this->schemaViolations($list, $mutated), "{$list}[] accepted a wrong type");
        }
    }

    /**
     * Mutation check, domain direction — an out-of-domain value for a closed field fails the schema.
     */
    public function testSchemaRejectsAnOutOfDomainValue(): void
    {
        $entry = $this->entriesFor('missing')[0];
        $mutated = $entry;
        $mutated['kind'] = 'not-a-real-kind';

        self::assertNotSame([], $this->schemaViolations('missing', $mutated), 'missing[] accepted an out-of-domain kind');
    }

    /**
     * The README "Report shapes" tables list EXACTLY the frozen fields of each list, in order — the
     * public contract cannot drift from the schema this test enforces.
     */
    public function testReadmeTablesMatchTheFrozenSchemaExactly(): void
    {
        $documented = $this->readmeFieldsByList();

        foreach (self::schema() as $list => $fields) {
            self::assertArrayHasKey($list, $documented, "README has no Report-shapes table for {$list}[]");
            self::assertSame(
                array_keys($fields),
                $documented[$list],
                "README {$list}[] table fields drifted from the schema",
            );
        }

        self::assertSame(
            array_keys(self::schema()),
            array_keys($documented),
            'README documents a different set of lists than the schema freezes',
        );
    }

    // --- helpers -----------------------------------------------------------------------------------

    /**
     * Collect every engine-generated entry for one report list across the whole corpus.
     *
     * @return list<array<string, mixed>>
     */
    private function entriesFor(string $list): array
    {
        $out = [];
        foreach ($this->corpus() as $report) {
            foreach ($report[$list] as $entry) {
                self::assertIsArray($entry);
                /** @var array<string, mixed> $entry */
                $out[] = $entry;
            }
        }

        return $out;
    }

    /**
     * The engine-generated corpus: each case is resolved and serialized, together covering every list,
     * every `kind`, and every `via`.
     *
     * @return list<array<string, mixed>>
     */
    private function corpus(): array
    {
        $resolver = new GraphResolver();
        $reports = [];
        foreach ($this->inputs() as $input) {
            $reports[] = $resolver->resolve($input)->toArray();
        }

        return $reports;
    }

    /**
     * The materialized inputs behind the corpus — the five §15 scenarios plus the constraint, oneOf,
     * deprecation, contract-manifest, legacy-capability and CRM-like cases.
     *
     * @return list<ResolutionInput>
     */
    private function inputs(): array
    {
        return [
            // §15-1 — missing required capability (missing:capability, resolved:capability, errors).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['command.provider', 'tool.registry']),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('tool.registry', 'Tool\\Registry', '0.1.0')],
                capabilityRequirements: [],
            ),
            // A required contract nobody implements (missing:contract, MILPA_CONTRACT_MISSING).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['milpa.runtime@0.3']),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A contract implemented only out of range (missing:contract, MILPA_CONTRACT_VERSION_UNSUPPORTED).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['milpa.persistence@^2.0']),
                versionManifests: [
                    new VersionManifest('milpa/persistence', '1.4.0', ['implements' => ['milpa.persistence@1.4.0']], ['provides' => []]),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // §15-2 — suggested capability missing (warnings:suggested-capability, resolved:capability).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['command.provider']),
                versionManifests: [
                    new VersionManifest(
                        package: 'milpa/command',
                        version: '0.1.0',
                        contracts: ['implements' => ['milpa.command@0.1']],
                        capabilities: [
                            'provides' => [['id' => 'command.provider', 'interface' => 'Cmd', 'contractVersion' => '0.1.0']],
                            'requires' => [],
                            'suggests' => ['audit.sink'],
                        ],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('command.provider', 'Cmd', '0.1.0')],
                capabilityRequirements: [],
            ),
            // §15-3 — legacy contract active (legacy:contract, migrationHints, resolved via=legacy).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['command.host@0.0'], allowedLegacyContracts: ['command.host']),
                versionManifests: [
                    new VersionManifest(
                        package: 'legacy/command-host',
                        version: '0.0.1',
                        contracts: ['implements' => ['command.host@0.0'], 'requires' => []],
                        capabilities: ['provides' => [], 'requires' => [], 'suggests' => []],
                        metadata: ['shape' => 'legacy-contracts'],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A legacy contract the host does NOT permit (allowedLegacyContracts: []) — the T3 gate: it
            // blocks via a missing[] legacy-contract entry (MILPA_LEGACY_NOT_ALLOWED, constraint null),
            // while the denial stays visible in legacy[] as permitted:false. Exercises the new missing
            // kind and proves constraint is genuinely nullable here.
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredContracts: ['command.host@0.0'], allowedLegacyContracts: []),
                versionManifests: [
                    new VersionManifest(
                        package: 'legacy/command-host',
                        version: '0.0.1',
                        contracts: ['implements' => ['command.host@0.0'], 'requires' => []],
                        capabilities: ['provides' => [], 'requires' => [], 'suggests' => []],
                        metadata: ['shape' => 'legacy-contracts'],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A legacy-shaped manifest that PROVIDES a required capability (legacy:capability, resolved via=legacy).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['legacy.cap'], allowedLegacyContracts: ['*']),
                versionManifests: [
                    new VersionManifest(
                        package: 'legacy/cap-host',
                        version: '0.0.1',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => [['id' => 'legacy.cap', 'interface' => 'L', 'contractVersion' => '0.0.1']]],
                        metadata: ['shape' => 'legacy-contracts'],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // §15-4 — unmet surface requirement (missing:surface-requirement).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', enabledSurfaces: ['mcp']),
                versionManifests: [
                    new VersionManifest('milpa/mcp-server', '0.1.0', ['implements' => []], ['provides' => []], surfaces: ['supports' => ['mcp']]),
                ],
                contractManifests: [],
                capabilityProvisions: [
                    new CapabilityProvision('tool.registry', 'I', '0.1.0'),
                    new CapabilityProvision('principal.resolver', 'I', '0.1.0'),
                ],
                capabilityRequirements: [],
                activeSurfaces: ['mcp'],
                environment: [
                    'surfaces' => [
                        ['surface' => 'mcp', 'requires' => ['tool.registry', 'mcp.transport', 'principal.resolver'], 'warnings' => []],
                    ],
                ],
            ),
            // §15-5 — exclusive conflict (conflicts, errors).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', requiredCapabilities: ['persistence.store']),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [
                    new CapabilityProvision('persistence.store', 'Store', '0.1.0', service: 'App\\MysqlStore', exclusive: true),
                    new CapabilityProvision('persistence.store', 'Store', '0.1.0', service: 'App\\SqliteStore', exclusive: true),
                ],
                capabilityRequirements: [],
            ),
            // A oneOf requirement satisfied by its alternative (resolved via=oneOf).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07'),
                versionManifests: [],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('log.syslog', 'Log', '0.1.0', service: 'App\\SyslogLogger')],
                capabilityRequirements: [new CapabilityRequirement('log.sink', 'Log', '*', ['log.file', 'log.syslog'])],
            ),
            // A declared deprecation (warnings:deprecation, errors).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07'),
                versionManifests: [
                    new VersionManifest('legacy/thing', '1.0.0', ['implements' => []], ['provides' => []], deprecations: ['old.command.host']),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // A contract manifest that wants an un-enabled surface (warnings:surface MILPA_SURFACE_NOT_ENABLED,
            // resolved:contract & capability-via-contract, learnLinks with academy + migration).
            new ResolutionInput(
                hostProfile: new HostProfile(
                    name: 'agent-ready',
                    version: '2026.07',
                    requiredContracts: ['milpa.command@0.1'],
                    requiredCapabilities: ['command.provider'],
                    enabledSurfaces: ['cli'],
                ),
                versionManifests: [
                    new VersionManifest('milpa/command', '0.1.0', ['implements' => ['milpa.command@0.1']], ['provides' => []]),
                ],
                contractManifests: [
                    new ContractManifest(
                        id: 'milpa.command',
                        version: '0.1',
                        requiresCapabilities: ['event.dispatcher'],
                        providesCapabilities: ['command.provider'],
                        suggestsCapabilities: ['audit.sink'],
                        surfaceRequirements: ['telegram'],
                        academyUrl: 'https://academy.milpa.lat/learn/fundamentos/contratos-grafo/',
                        migrationUrl: 'https://academy.milpa.lat/artifacts/#atomo',
                    ),
                ],
                capabilityProvisions: [new CapabilityProvision('event.dispatcher', 'E', '0.1.0')],
                capabilityRequirements: [],
                activeSurfaces: ['cli'],
            ),
            // An enabled surface fully satisfied but carrying a declared warning (resolved:surface,
            // warnings:surface with an author-defined open code).
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07', enabledSurfaces: ['http']),
                versionManifests: [
                    new VersionManifest('milpa/http', '0.1.0', ['implements' => []], ['provides' => []], surfaces: ['supports' => ['http']]),
                ],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('http.router', 'R', '0.1.0')],
                capabilityRequirements: [],
                activeSurfaces: ['http'],
                environment: [
                    'surfaces' => [
                        [
                            'surface' => 'http',
                            'requires' => ['http.router'],
                            'warnings' => [
                                ['code' => 'HTTP_SCOPES_NOT_ENFORCED', 'message' => 'HTTP routes do not enforce Operation scopes in this profile.'],
                            ],
                        ],
                    ],
                ],
            ),
            // A dependency cycle (conflicts:dependency-cycle, MILPA_DEPENDENCY_CYCLE, status blocked):
            // cycle/a and cycle/b require each other's capability, so neither can boot first; the
            // independent third package keeps loadOrder[] populated while the members stay out of it.
            new ResolutionInput(
                hostProfile: new HostProfile('agent-ready', '2026.07'),
                versionManifests: [
                    new VersionManifest(
                        package: 'cycle/a',
                        version: '1.0.0',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => ['cap.a'], 'requires' => ['cap.b']],
                    ),
                    new VersionManifest(
                        package: 'cycle/b',
                        version: '1.0.0',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => ['cap.b'], 'requires' => ['cap.a']],
                    ),
                    new VersionManifest(
                        package: 'cycle/standalone',
                        version: '1.0.0',
                        contracts: ['implements' => []],
                        capabilities: ['provides' => []],
                    ),
                ],
                contractManifests: [],
                capabilityProvisions: [],
                capabilityRequirements: [],
            ),
            // An accepted risk with an expiry but NO evaluatedAt clock (warnings:risk-expiry — the
            // MILPA_RISK_EXPIRY_UNEVALUATED oversight — plus the accepted surface warning it rides on).
            new ResolutionInput(
                hostProfile: new HostProfile(
                    name: 'agent-ready',
                    version: '2026.07',
                    enabledSurfaces: ['http'],
                    acceptedRisks: [new AcceptedRisk('HTTP_SCOPES_NOT_ENFORCED', 'Enforced at the gateway; reviewed 2026-07.', '2026-12-31')],
                ),
                versionManifests: [
                    new VersionManifest('milpa/http', '0.1.0', ['implements' => []], ['provides' => []], surfaces: ['supports' => ['http']]),
                ],
                contractManifests: [],
                capabilityProvisions: [new CapabilityProvision('http.router', 'R', '0.1.0')],
                capabilityRequirements: [],
                activeSurfaces: ['http'],
                environment: [
                    'surfaces' => [
                        [
                            'surface' => 'http',
                            'requires' => ['http.router'],
                            'warnings' => [
                                ['code' => 'HTTP_SCOPES_NOT_ENFORCED', 'message' => 'HTTP routes do not enforce Operation scopes in this profile.'],
                            ],
                        ],
                    ],
                ],
            ),
        ];
    }

    /**
     * Validate one entry against its list schema; returns a list of human-readable violations (empty
     * when the entry conforms). Key-set drift short-circuits: once the shape is wrong, per-field type
     * noise would only obscure the real fault.
     *
     * @param array<string, mixed> $entry
     *
     * @return list<string>
     */
    private function schemaViolations(string $list, array $entry): array
    {
        $schema = self::schema()[$list];
        $expectedKeys = array_keys($schema);
        if (array_keys($entry) !== $expectedKeys) {
            return [sprintf('keys [%s] != expected [%s]', implode(',', array_keys($entry)), implode(',', $expectedKeys))];
        }

        $violations = [];
        foreach ($schema as $field => $spec) {
            $type = $spec[0];
            $domain = $spec[1] ?? null;
            $value = $entry[$field];

            if (!$this->typeOk($type, $value)) {
                $violations[] = sprintf('%s: expected type %s, got %s', $field, $type, get_debug_type($value));

                continue;
            }

            if ($domain !== null && is_string($value)) {
                $allowed = $domain === 'catalog' ? ErrorCatalog::codes() : $domain;
                if (!in_array($value, $allowed, true)) {
                    $violations[] = sprintf('%s: value "%s" is out of domain', $field, $value);
                }
            }
        }

        return $violations;
    }

    private function typeOk(string $type, mixed $value): bool
    {
        return match ($type) {
            'string' => is_string($value),
            'non-empty-string' => is_string($value) && $value !== '',
            '?string' => $value === null || is_string($value),
            'bool' => is_bool($value),
            'string[]' => $this->isListOf($value, 'is_string'),
            'array[]' => $this->isListOf($value, 'is_array'),
            'array' => is_array($value),
            default => false,
        };
    }

    /**
     * @param callable(mixed): bool $predicate
     */
    private function isListOf(mixed $value, callable $predicate): bool
    {
        if (!is_array($value) || !array_is_list($value)) {
            return false;
        }
        foreach ($value as $item) {
            if (!$predicate($item)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Parse the README "Report shapes" section: for each `#### `list[]`` subsection, the ordered list
     * of field names taken from the first column of its table.
     *
     * @return array<string, list<string>>
     */
    private function readmeFieldsByList(): array
    {
        $md = file_get_contents(dirname(__DIR__, 2) . '/README.md');
        self::assertIsString($md, 'README.md is unreadable');

        $start = strpos($md, '## Report shapes');
        self::assertNotFalse($start, 'README has no "## Report shapes" section');
        $section = substr($md, $start);
        $nextH2 = strpos($section, "\n## ", 4);
        if ($nextH2 !== false) {
            $section = substr($section, 0, $nextH2);
        }

        preg_match_all('/####\s+`([a-zA-Z]+)\[\]`(.*?)(?=\n####|\z)/s', $section, $blocks, PREG_SET_ORDER);

        $out = [];
        foreach ($blocks as $block) {
            $list = $block[1];
            preg_match_all('/^\|\s*`([^`]+)`\s*\|/m', $block[2], $rows);
            $out[$list] = $rows[1];
        }

        return $out;
    }
}
